# Specifies the API version to use for the Deployment object
apiVersion: apps/v1

# Declares that this configuration is for a Deployment object
kind: Deployment

# Metadata holds the name and other identifying info
metadata:
  name: kubernetes-test-app  # The name of the Deployment

spec:
  replicas: 2  # Number of pod replicas to run (i.e., 2 pods)

  # Selector tells the Deployment how to find the Pods it manages
  selector:
    matchLabels:
      app: kubernetes-test-app  # Must match the labels defined in the Pod template

  # Template defines the pod specification (how each pod should look)
  template:
    metadata:
      labels:
        app: kubernetes-test-app  # Label assigned to Pods. Used by selectors and Services

    spec:
      containers:
      - name: kubernetes-test-app  # Name of the container inside the Pod
        image: prakash3112/kubernetes-test-app:v3  # Docker image to use for the container

        # Resource limits for the container
        resources:
          limits:
            memory: "128Mi"  # Max memory the container can use
            cpu: "500m"      # Max CPU the container can use (500 millicores = 0.5 cores)

        # Port that the container exposes to other Pods or services
        ports:
        - containerPort: 5000  # The container listens on port 5000
